language: node_js
sudo: false
node_js:
- "0.10"
- "4"
before_script:
- npm install -g codeclimate-test-reporter
script:
- npm run lint
- npm run coverage
- npm run functional
after_script:
- npm run coverage
- PATH=$NVM_BIN:$PATH codeclimate-test-reporter < ./coverage/lcov.info
